name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MinGW-w64
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          static: false

      - name: Show GCC version
        run: gcc --version


      - name: Build
        shell: cmd
        working-directory: emulator
        run: build.bat

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: CasioEmuX-build
          path: |
            **/*.exe
            **/*.dll
            !**/node_modules/**
            !**/.git/**
